name: Docker Build & Publish
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
 
      - name: Create .env file
        run: |
            echo "API_URL=${{ secrets.API_URL }}" >> .env
            echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" >> .env
            echo ".env file created with API_URL and MAPBOX_TOKEN"
 
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
 
      - name: Build Docker Image
        run: docker build -t mariguapo/nature-api:${{ github.sha }} .
 
      - name: Tag Latest
        run: docker tag mariguapo/nature-api:${{ github.sha }} mariguapo/nature-api:latest
 
      - name: Push Docker Image
        run: |
          docker push mariguapo/nature-api:${{ github.sha }}
          docker push mariguapo/nature-api:latest